export default { 
	UPDATE_SIMULATION_MESSAGE_1: "UPDATE_SIMULATION_MESSAGE_1",
	UPDATE_SIMULATION_MESSAGE_2: "UPDATE_SIMULATION_MESSAGE_2",
	UPDATE_SIMULATION_MESSAGE_3: "UPDATE_SIMULATION_MESSAGE_3"
};