const contentFileIndex = { 
	avedon1: require('./avedon1.jpg'),
	avedon2: require('./avedon2.jpg'),
	avedon3: require('./avedon3.jpg'),
	avedon4: require('./avedon4.jpg'),
	margaret1: require('./margaret1.jpg'),
	margaret2: require('./margaret2.jpg'),
	margaret3: require('./margaret3.jpg'),
	margaret4: require('./margaret4.jpg'),
	margaret5: require('./margaret5.jpg'),
	parks1: require('./parks1.jpg'),
	parks2: require('./parks2.jpg'),
	parks3: require('./parks3.jpg'),
	parks4: require('./parks4.jpg'),
	parks5: require('./parks5.jpg'),
	parks6: require('./parks6.jpg'),
	penn1: require('./penn1.jpg'),
	penn2: require('./penn2.jpg'),
	penn3: require('./penn3.jpg'),
	penn4: require('./penn4.jpg'),
	penn5: require('./penn5.jpg'),
	penn6: require('./penn6.jpg'),
	reed1: require('./reed1.jpg'),
	reed2: require('./reed2.jpg'),
	reed3: require('./reed3.jpg'),
	reed4: require('./reed4.jpg'),
	reed5: require('./reed5.jpg'),
	reed6: require('./reed6.jpg'),
	reed7: require('./reed7.jpg'),
	reed8: require('./reed8.jpg'),
	reed9: require('./reed9.jpg'),
	shabazz1: require('./shabazz1.jpg'),
	shabazz2: require('./shabazz2.jpg'),
	shabazz3: require('./shabazz3.jpg'),
	shabazz4: require('./shabazz4.jpg'),
	shabazz5: require('./shabazz5.jpg'),
	shabazz6: require('./shabazz6.jpg'),
	shabazz7: require('./shabazz7.jpg'),
	shabazz8: require('./shabazz8.jpg')
}

export default contentFileIndex;